# Copyright (c) Dennis Shevtsov. All rights reserved.
# Licensed under the MIT License.
# See LICENSE in the project root for license information.

version: '3.4'

services:
  quartz-sample-web:
    container_name: quartz-sample-web
    image: quartz-sample-web
    build:
      context: .
      dockerfile: src/QuartzSample.Web/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=5001
      - CONNECTIONSTRINGS__QUARTZ=Host=quartz-sample-db;Port=5432;Database=quartz-sample-db;Username=dev;Password=dev;Include Error Detail=true
    ports:
      - "5001:5001"
    depends_on:
      - quartz-sample-db
  quartz-sample-db:
    container_name: quartz-sample-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=quartz-sample-db
    volumes:
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d # postgres runs scripts in this directory after creating the db
