version: '3.4'

services:
  quartz-sample-web:
    container_name: quartz-sample-web
    image: quartz-sample-web
    build:
      context: .
      dockerfile: src/QuartzSample.Web/Dockerfile
    environment:
      - ASPNETCORE_HTTP_PORTS=5001
    ports:
      - "5001:5001"
  quartz-sample-db:
    container_name: quartz-sample-db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=quartz-sample-db
    volumes:
      - type: bind
        source: ./init
        target: /docker-entrypoint-initdb.d # postgres runs scripts in this directory after creating the db
